In [ ]:
## This is simple practise on MNIST dataset using keras. 
## MNIST data has hand written numbers. 
## The task is to classify the image as number ranging from 0-9

In [ ]:
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers

In [ ]:
## Preparing the Data 

num_classes = 10
input_shape = (28, 28, 1) ## Each image has 784 [28 * 28]

## Split train and test data 
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

In [ ]:
## Scale images to [0, 1] range 
x_train = x_train.astype('float32') / 255
x_test = x_test.astype('float32') / 255
print (x_test)

[[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]


In [ ]:
x_train = np.expand_dims(x_train, -1) ## Expand the shape of an array. -1 is the axis . 
x_test = np.expand_dims(x_test, -1)

print ('X Train Shape :', x_train.shape)
print (x_train.shape[0], 'Train Samples')
print (x_test.shape[0], "Test Samples")



X Train Shape : (60000, 28, 28, 1)
60000 Train Samples
10000 Test Samples


In [ ]:
## convert Class vectors to Binary class matrices 

y_train = keras.utils.to_categorical(y_train, num_classes)
y_test = keras.utils.to_categorical(y_test, num_classes)
print (y_test[0])

[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]


In [ ]:
## Build the Model 

model = keras.Sequential([
              keras.Input(shape=input_shape),
              layers.Conv2D(32, kernel_size=(3,3), activation='relu'),
              layers.MaxPooling2D(pool_size=(2,2)),
              layers.Conv2D(64, kernel_size=(3,3), activation='relu'),
              layers.MaxPooling2D(pool_size=(2,2)),
              layers.Flatten(),
              layers.Dropout(0.3),
              layers.Dense(num_classes, activation='softmax'),
])

model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_2 (Conv2D)            (None, 26, 26, 32)        320       
_________________________________________________________________
max_pooling2d_2 (MaxPooling2 (None, 13, 13, 32)        0         
_________________________________________________________________
conv2d_3 (Conv2D)            (None, 11, 11, 64)        18496     
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 5, 5, 64)          0         
_________________________________________________________________
flatten_1 (Flatten)          (None, 1600)              0         
_________________________________________________________________
dropout_1 (Dropout)          (None, 1600)              0         
_________________________________________________________________
dense_1 (Dense)              (None, 10)               

In [ ]:
## Train the model 

batch_size = 128
epochs = 15

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.1)

Epoch 1/15
422/422 [==============================] - 35s 83ms/step - loss: 0.3289 - accuracy: 0.9008 - val_loss: 0.0868 - val_accuracy: 0.9763
Epoch 2/15
422/422 [==============================] - 35s 82ms/step - loss: 0.1008 - accuracy: 0.9692 - val_loss: 0.0647 - val_accuracy: 0.9835
Epoch 3/15
422/422 [==============================] - 35s 82ms/step - loss: 0.0775 - accuracy: 0.9759 - val_loss: 0.0537 - val_accuracy: 0.9857
Epoch 4/15
422/422 [==============================] - 34s 82ms/step - loss: 0.0641 - accuracy: 0.9804 - val_loss: 0.0507 - val_accuracy: 0.9863
Epoch 5/15
422/422 [==============================] - 34s 81ms/step - loss: 0.0556 - accuracy: 0.9825 - val_loss: 0.0453 - val_accuracy: 0.9882
Epoch 6/15
422/422 [==============================] - 35s 82ms/step - loss: 0.0487 - accuracy: 0.9845 - val_loss: 0.0369 - val_accuracy: 0.9900
Epoch 7/15
422/422 [==============================] - 35s 82ms/step - loss: 0.0449 - accuracy: 0.9852 - val_loss: 0.0362 - val_accuracy:

In [ ]:
## Evaluate the Trained model 

score = model.evaluate(x_test, y_test, verbose=0)
print("Test loss:", score[0])
print("Test accuracy:", score[1])

Test loss: 0.024402454495429993
Test accuracy: 0.9916999936103821
